version: 2

models:
  - name: mart_real_world_actuals_weekly
    description: |
      Real-world actuals mart - weekly player performance in physical stats (no fantasy scoring).

      **Grain**: One row per player per season per week
      **Source**: fact_player_stats (pivoted from long to wide form)

      Part of 2×2 model:
      - This mart: Real-world actuals (yards, TDs, receptions, etc.)
      - Partner mart: mart_fantasy_actuals_weekly (applies scoring rules)

      Provides denormalized player/team attributes via dimension joins.

    columns:
      - name: player_id
        description: Canonical player identifier (FK to dim_player)
        tests:
          - not_null
          - relationships:
              to: ref('dim_player')
              field: player_id
              config:
                where: "player_id != -1"  # Allow unmapped players

      - name: player_key
        description: Composite player identifier for grain uniqueness
        tests:
          - not_null

      - name: season
        description: NFL season year
        tests:
          - not_null

      - name: week
        description: Week number (1-22, includes playoffs)
        tests:
          - not_null

      - name: season_type
        description: Season type (REG, POST, WC, DIV, CON, SB, PRE)
        tests:
          - not_null
          - accepted_values:
              values: ['REG', 'POST', 'WC', 'DIV', 'CON', 'SB', 'PRE']

      - name: position
        description: Player position
        tests:
          - not_null

      - name: display_name
        description: Player display name from dim_player
        tests:
          - not_null:
              config:
                where: "player_id != -1"  # Unmapped players may lack display_name

      - name: games_played
        description: Games played (always 1 for weekly grain)
        tests:
          - not_null
          - accepted_values:
              values: [1]

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - player_key
            - season
            - week
            - season_type
          config:
            severity: error
            error_if: ">0"

  - name: mart_fantasy_actuals_weekly
    description: |
      Fantasy actuals mart - weekly player performance with fantasy scoring applied.

      **Grain**: One row per player per season per week
      **Source**: mart_real_world_actuals_weekly (with scoring rules applied)

      Part of 2×2 model:
      - Real-world base: mart_real_world_actuals_weekly (physical stats)
      - Fantasy scoring: This mart (applies dim_scoring_rule to calculate points)

      League scoring: Half-PPR + IDP
      - Passing: 0.04/yard, 4/TD, -2/INT, 2/2PT
      - Rushing: 0.1/yard, 6/TD, -2/fumble lost, 2/2PT
      - Receiving: 0.5/reception (half-PPR), 0.1/yard, 6/TD, -2/fumble lost, 2/2PT
      - IDP: Various tackle/sack/turnover scoring

    columns:
      - name: player_id
        description: Canonical player identifier (FK to dim_player)
        tests:
          - not_null
          - relationships:
              to: ref('dim_player')
              field: player_id
              config:
                where: "player_id != -1"  # Allow unmapped players

      - name: player_key
        description: Composite player identifier for grain uniqueness
        tests:
          - not_null

      - name: season
        description: NFL season year
        tests:
          - not_null

      - name: week
        description: Week number (1-22, includes playoffs)
        tests:
          - not_null

      - name: season_type
        description: Season type (REG, POST, WC, DIV, CON, SB, PRE)
        tests:
          - not_null

      - name: position
        description: Player position
        tests:
          - not_null

      - name: display_name
        description: Player display name
        tests:
          - not_null:
              config:
                where: "player_id != -1"  # Unmapped players may lack display_name

      - name: fantasy_points
        description: |
          Total fantasy points calculated from real-world stats and league scoring rules.
          Includes offensive (passing/rushing/receiving) and defensive (IDP) scoring.
        tests:
          - not_null

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - player_key
            - season
            - week
            - season_type
          config:
            severity: error
            error_if: ">0"

  - name: mart_contract_snapshot_current
    description: |
      Contract snapshot mart - current contract obligations by year (transaction-derived).

      **Grain**: One row per player per franchise per contract period per obligation year
      **Source**: dim_player_contract_history (expands contract_split_array into year-by-year rows)

      Shows each player's current active contract broken down by year, including:
      - Annual cap hit for each obligation year
      - Remaining contract value from each year forward
      - Dead cap liability if cut before that year
      - Contract metadata (type, rookie flag, effective dates)

      **Extension Handling**: contract_split_array already contains full remaining schedule
      per league accounting conventions (e.g., 6-6-24 = 2 base years + 1 extension year).

      **Use Cases**:
      - Salary cap planning: Future year obligations
      - Dead cap analysis: Cut liability scenarios
      - Contract timeline: Expiration tracking
      - Rookie contract management: Extension decisions

    columns:
      - name: player_id
        description: Canonical player identifier (FK to dim_player_id_xref)
        tests:
          - not_null
          - relationships:
              to: ref('dim_player_id_xref')
              field: player_id

      - name: franchise_id
        description: FK to dim_franchise (franchise owning the contract)
        tests:
          - not_null
          - relationships:
              to: ref('dim_franchise')
              field: franchise_id

      - name: contract_period
        description: Sequential contract number for this player (1, 2, 3...)
        tests:
          - not_null

      - name: obligation_year
        description: Calendar year of the obligation (2023-2028)
        tests:
          - not_null

      - name: year_position
        description: Position within this contract (1, 2, 3, ...)
        tests:
          - not_null

      - name: annual_cap_hit
        description: Cap hit for this specific year (from contract_split_array)
        tests:
          - not_null

      - name: years_remaining
        description: Years left in contract from this year forward (including this year)
        tests:
          - not_null

      - name: remaining_contract_value
        description: Sum of all cap hits from this year forward
        tests:
          - not_null

      - name: dead_cap_if_cut_before_year
        description: Dead cap liability if cut before this year starts
        tests:
          - not_null

      - name: contract_type
        description: Contract classification (rookie, faad, fasa, trade_acquired, extension, etc.)
        tests:
          - not_null
          - accepted_values:
              values:
                - rookie
                - faad
                - fasa
                - trade_acquired
                - extension
                - franchise_tag
                - waiver_claim
                - other

      - name: is_rookie_contract
        description: Flag for rookie contracts
        tests:
          - not_null

      - name: contract_history_key
        description: FK to dim_player_contract_history
        tests:
          - not_null
          - relationships:
              to: ref('dim_player_contract_history')
              field: contract_history_key

      - name: transaction_id_unique
        description: FK to fact_league_transactions (audit trail)
        tests:
          - not_null
          - relationships:
              to: ref('fact_league_transactions')
              field: transaction_id_unique

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - player_id
            - franchise_id
            - contract_period
            - obligation_year
          config:
            severity: error
            error_if: ">0"

  - name: mart_contract_snapshot_history
    description: |
      Contract snapshot mart - historical point-in-time contract obligations (commissioner sheet snapshots).

      **Grain**: One row per player per franchise per snapshot date per obligation year
      **Source**: stg_sheets__contracts_active (direct from commissioner's CONTRACTS_ACTIVE sheet)

      Provides point-in-time historical view of contract obligations as recorded in the
      commissioner's CONTRACTS_ACTIVE sheet at various snapshot dates.

      **Key Differences from mart_contract_snapshot_current**:
      - Uses direct commissioner sheet snapshots (not derived from transaction log)
      - Includes snapshot_date as grain component (enables time-series)
      - Shows obligations as commissioner recorded them at each point in time
      - May include manual corrections not yet in transaction log

      **Use Cases**:
      - Historical cap space: Obligations as of specific past dates
      - Validation: Compare transaction-derived vs commissioner snapshots
      - Trend analysis: Evolution of obligations over time
      - Commissioner audit: Track changes between snapshot dates

    columns:
      - name: player_id
        description: Canonical player identifier (FK to dim_player_id_xref, -1 if unmapped)
        tests:
          - relationships:
              to: ref('dim_player_id_xref')
              field: player_id
              config:
                where: "player_id != -1 and not is_unmapped_player"

      - name: franchise_id
        description: FK to dim_franchise (may be null if unmapped)
        tests:
          - relationships:
              to: ref('dim_franchise')
              field: franchise_id
              config:
                where: "franchise_id is not null and not is_unmapped_franchise"

      - name: snapshot_date
        description: Date of this snapshot from CONTRACTS_ACTIVE sheet
        tests:
          - not_null

      - name: obligation_year
        description: Calendar year of the obligation (2023-2028)
        tests:
          - not_null

      - name: cap_hit
        description: Annual obligation for this year (from commissioner sheet)
        tests:
          - not_null

      - name: player_key
        description: Composite identifier for grain uniqueness (handles unmapped players)
        tests:
          - not_null

      - name: rfa
        description: RFA status flag (from commissioner sheet)

      - name: franchise_tag
        description: Franchise tag flag (from commissioner sheet)

      - name: is_unmapped_player
        description: Flag indicating player not found in crosswalk
        tests:
          - not_null

      - name: is_unmapped_franchise
        description: Flag indicating franchise not resolved
        tests:
          - not_null

      - name: snapshot_year
        description: Year extracted from snapshot_date
        tests:
          - not_null

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - player_key
            - franchise_id
            - snapshot_date
            - obligation_year
          config:
            severity: error
            error_if: ">0"
