# dbt-opiner configuration
# See https://pypi.org/project/dbt-opiner/ for available options
#
# File exclusions are handled here for portability and observability
# Test files are excluded - they're not dbt project nodes

opinions_config:
  ignore_opinions: ""
  ignore_files: {}
