# dbt-opiner configuration
# See https://pypi.org/project/dbt-opiner/ for available options
#
# File exclusions are handled here for portability and observability
# Test files are excluded - they're not dbt project nodes

opinions_config:
  ignore_opinions: ""
  ignore_files:
    # sqlglot parser limitations (DuckDB regex, column ambiguity)
    O003: >-
      .*/dbt/ff_data_transform/models/(staging/(stg_sleeper__rosters|stg_sheets__transactions)|core/intermediate/int_pick_comp_.*)\.sql
    O004: >-
      .*/dbt/ff_data_transform/models/(staging/(stg_sleeper__rosters|stg_sheets__transactions)|core/intermediate/int_pick_comp_.*)\.sql
    O007: >-
      .*/dbt/ff_data_transform/models/(staging/(stg_sleeper__rosters|stg_sheets__transactions)|core/intermediate/int_pick_comp_.*)\.sql

files:
  sql: .*/dbt/ff_data_transform/(models|macros|snapshots)/.*\.sql$
  yaml: .*/dbt/ff_data_transform/(models|snapshots)/.*\.(yml|yaml)$
  md: .*/dbt/ff_data_transform/docs/.*\.md$
