# dbt-opiner configuration
# See https://pypi.org/project/dbt-opiner/ for available options
#
# File exclusions are handled here for portability and observability
# Test files are excluded - they're not dbt project nodes

opinions_config:
  ignore_opinions: ""

files:
  sql: .*/dbt/ff_data_transform/(models|macros|snapshots)/.*\.sql$
  yaml: .*/dbt/ff_data_transform/(models|snapshots)/.*\.(yml|yaml)$
  md: .*/dbt/ff_data_transform/docs/.*\.md$
