extends: default

rules:
  line-length:
    max: 120
    level: warning
  document-start: disable
  truthy:
    allowed-values: ["true", "false", "yes", "no"]
  comments:
    min-spaces-from-content: 2
  indentation:
    spaces: 2
    indent-sequences: true
  brackets:
    max-spaces-inside: 1
  braces:
    max-spaces-inside: 1

ignore: |
  .venv/
  venv/
  data/
  .github/actionlint.yaml
  dbt/
