---
ignore:
  - .venv/
  - venv/
  - data/
  - .github/actionlint.yaml
  - dbt/

extends: default

rules:
  line-length:
    level: warning
  document-start: enable
  truthy: enable
  indentation:
    spaces: consistent
    indent-sequences: true
  brackets:
    max-spaces-inside: 1
  braces:
    max-spaces-inside: 1
