name: ff_analytics
version: "1.0"
config-version: 2

profile: ff_duckdb

vars:
  external_root: "{{ env_var('EXTERNAL_ROOT', 'gs://ff-analytics/mart') }}"

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

models:
  +materialized: table
  # Model-specific configs are defined in individual model files
  # Directory-level configs will be added as needed
