name: ff_analytics
version: "1.0"
config-version: 2
profile: ff_duckdb

vars:
  external_root: "{{ env_var('EXTERNAL_ROOT', 'data/raw') }}"

  # Latest completed rookie draft season (v2 architecture)
  # Update this ONCE when draft completes (no SQL changes needed)
  # Historical: seasons with actual draft data (2012-2024)
  # Prospective: seasons with only FAAD projections (2025+)
  latest_completed_draft_season: 2024

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

# Exclude archived seeds and models
seeds:
  ff_analytics:
    _archive:
      +enabled: false

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +materialized: table
  # Model-specific configs are defined in individual model files
  # Directory-level configs will be added as needed

tests:
  +severity: error
  +tags: ["data_quality", "franchise_mapping"]
