# Sleeper scoring rules exported on 2025-09-24T23:30:42.777306Z
# Source: league_data.json (league_id: 1230330435511275520)
scoring:
  sack: 0.5
  fgm_40_49: 0.0
  fgm_yds: 0.1
  pass_int: -2.0
  pts_allow_0: 15.0
  pass_2pt: 2.0
  st_td: 0.0
  pr_td: 0.0
  rec_td: 6.0
  idp_blk_kick: 12.0
  fgm_30_39: 0.0
  xpmiss: -1.0
  rush_td: 6.0
  def_pr_td: 0.0
  idp_tkl: 0.5
  rec_2pt: 2.0
  idp_tkl_loss: 1.5
  idp_tkl_solo: 0.0
  st_fum_rec: 0.0
  fgmiss: 0.0
  ff: 0.0
  idp_int: 6.0
  fgmiss_30_39: -2.0
  rec: 0.5
  idp_safe: 9.0
  pts_allow_14_20: 2.25
  fgm_0_19: 0.0
  idp_def_td: 6.0
  def_kr_td: 0.0
  int: 1.5
  def_st_fum_rec: 1.5
  fum_lost: -2.0
  pts_allow_1_6: 9.0
  fgmiss_20_29: -3.0
  idp_sack: 1.5
  fgm_20_29: 0.0
  pts_allow_21_27: 0.0
  xpm: 1.0
  fgmiss_0_19: -3.0
  rush_2pt: 2.0
  fum_rec: 1.5
  idp_pass_def: 3.0
  def_st_td: 6.0
  fgm_50p: 0.0
  def_td: 6.0
  idp_fum_rec: 6.0
  safe: 3.0
  pass_yd: 0.04
  fgmiss_40_49: -1.0
  blk_kick: 3.0
  pass_td: 4.0
  idp_qb_hit: 1.0
  rush_yd: 0.1
  fum: 0.0
  pts_allow_28_34: -2.25
  pts_allow_35p: -4.5
  fum_rec_td: 6.0
  rec_yd: 0.1
  def_st_ff: 0.0
  pts_allow_7_13: 4.5
  idp_ff: 3.0
  st_ff: 0.0
  idp_tkl_ast: 0.0
